# Generated by Django 3.1.7 on 2021-08-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210822_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Division_Choice',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi'), ('Chattrogram', 'Chattrogram'), ('Mymansin', 'Mymansin')], max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Tangail', 'Tangail'), ('Gazipur', 'Gazipur'), ('Rajshahi', 'Rajshahi'), ('Chattrogram', 'Chattrogram'), ('Mymansin', 'Mymansin')], max_length=200),
        ),
    ]
